
package com.aasoapexample.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatelogSer", targetNamespace = "http://service.aasoapexample.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatelogSer {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.aasoapexample.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductServ", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.GetProductServ")
    @ResponseWrapper(localName = "getProductServResponse", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.GetProductServResponse")
    @Action(input = "http://service.aasoapexample.com/ProductCatelogSer/getProductServRequest", output = "http://service.aasoapexample.com/ProductCatelogSer/getProductServResponse")
    public Product getProductServ(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProductServ", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.AddProductServ")
    @ResponseWrapper(localName = "addProductServResponse", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.AddProductServResponse")
    @Action(input = "http://service.aasoapexample.com/ProductCatelogSer/addProductServRequest", output = "http://service.aasoapexample.com/ProductCatelogSer/addProductServResponse")
    public boolean addProductServ(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "Product", targetNamespace = "")
    @RequestWrapper(localName = "updateProductServ", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.UpdateProductServ")
    @ResponseWrapper(localName = "updateProductServResponse", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.UpdateProductServResponse")
    @Action(input = "http://service.aasoapexample.com/ProductCatelogSer/updateProductServRequest", output = "http://service.aasoapexample.com/ProductCatelogSer/updateProductServResponse")
    public boolean updateProductServ(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.aasoapexample.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductServ", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.GetAllProductServ")
    @ResponseWrapper(localName = "getAllProductServResponse", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.GetAllProductServResponse")
    @Action(input = "http://service.aasoapexample.com/ProductCatelogSer/getAllProductServRequest", output = "http://service.aasoapexample.com/ProductCatelogSer/getAllProductServResponse")
    public List<Product> getAllProductServ();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProductServ", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.DeleteProductServ")
    @ResponseWrapper(localName = "deleteProductServResponse", targetNamespace = "http://service.aasoapexample.com/", className = "com.aasoapexample.service.DeleteProductServResponse")
    @Action(input = "http://service.aasoapexample.com/ProductCatelogSer/deleteProductServRequest", output = "http://service.aasoapexample.com/ProductCatelogSer/deleteProductServResponse")
    public boolean deleteProductServ(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
