
package com.aasoapexample.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductCatelogServiceService", targetNamespace = "http://service.aasoapexample.com/", wsdlLocation = "http://localhost:8080/aasoapmysqlexampl/ProductCatelogServiceService?wsdl")
public class ProductCatelogServiceService
    extends Service
{

    private final static URL PRODUCTCATELOGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTCATELOGSERVICESERVICE_EXCEPTION;
    private final static QName PRODUCTCATELOGSERVICESERVICE_QNAME = new QName("http://service.aasoapexample.com/", "ProductCatelogServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/aasoapmysqlexampl/ProductCatelogServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCATELOGSERVICESERVICE_WSDL_LOCATION = url;
        PRODUCTCATELOGSERVICESERVICE_EXCEPTION = e;
    }

    public ProductCatelogServiceService() {
        super(__getWsdlLocation(), PRODUCTCATELOGSERVICESERVICE_QNAME);
    }

    public ProductCatelogServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCATELOGSERVICESERVICE_QNAME, features);
    }

    public ProductCatelogServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCATELOGSERVICESERVICE_QNAME);
    }

    public ProductCatelogServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCATELOGSERVICESERVICE_QNAME, features);
    }

    public ProductCatelogServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCatelogServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductCatelogSer
     */
    @WebEndpoint(name = "ProductCatelogServicePort")
    public ProductCatelogSer getProductCatelogServicePort() {
        return super.getPort(new QName("http://service.aasoapexample.com/", "ProductCatelogServicePort"), ProductCatelogSer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCatelogSer
     */
    @WebEndpoint(name = "ProductCatelogServicePort")
    public ProductCatelogSer getProductCatelogServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.aasoapexample.com/", "ProductCatelogServicePort"), ProductCatelogSer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCATELOGSERVICESERVICE_EXCEPTION!= null) {
            throw PRODUCTCATELOGSERVICESERVICE_EXCEPTION;
        }
        return PRODUCTCATELOGSERVICESERVICE_WSDL_LOCATION;
    }

}
