
package com.aasoapexample.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductDao", targetNamespace = "http://dao.aasoapexample.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.aasoapexample.dao.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.GetProductResponse")
    @Action(input = "http://dao.aasoapexample.com/ProductDao/getProductRequest", output = "http://dao.aasoapexample.com/ProductDao/getProductResponse")
    public Product getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.aasoapexample.dao.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProduct", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.GetAllProduct")
    @ResponseWrapper(localName = "getAllProductResponse", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.GetAllProductResponse")
    @Action(input = "http://dao.aasoapexample.com/ProductDao/getAllProductRequest", output = "http://dao.aasoapexample.com/ProductDao/getAllProductResponse")
    public List<Product> getAllProduct();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.AddProductResponse")
    @Action(input = "http://dao.aasoapexample.com/ProductDao/addProductRequest", output = "http://dao.aasoapexample.com/ProductDao/addProductResponse")
    public String addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.DeleteProductResponse")
    @Action(input = "http://dao.aasoapexample.com/ProductDao/deleteProductRequest", output = "http://dao.aasoapexample.com/ProductDao/deleteProductResponse")
    public String deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "Product", targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://dao.aasoapexample.com/", className = "com.aasoapexample.dao.UpdateProductResponse")
    @Action(input = "http://dao.aasoapexample.com/ProductDao/updateProductRequest", output = "http://dao.aasoapexample.com/ProductDao/updateProductResponse")
    public String updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
