
package com.aasoapexample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductCatelogContImplService", targetNamespace = "http://aasoapexample.com/", wsdlLocation = "http://localhost:8080/aasoapmysqlexampl/ProductCatelogContImplService?wsdl")
public class ProductCatelogContImplService
    extends Service
{

    private final static URL PRODUCTCATELOGCONTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTCATELOGCONTIMPLSERVICE_EXCEPTION;
    private final static QName PRODUCTCATELOGCONTIMPLSERVICE_QNAME = new QName("http://aasoapexample.com/", "ProductCatelogContImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/aasoapmysqlexampl/ProductCatelogContImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCATELOGCONTIMPLSERVICE_WSDL_LOCATION = url;
        PRODUCTCATELOGCONTIMPLSERVICE_EXCEPTION = e;
    }

    public ProductCatelogContImplService() {
        super(__getWsdlLocation(), PRODUCTCATELOGCONTIMPLSERVICE_QNAME);
    }

    public ProductCatelogContImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCATELOGCONTIMPLSERVICE_QNAME, features);
    }

    public ProductCatelogContImplService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCATELOGCONTIMPLSERVICE_QNAME);
    }

    public ProductCatelogContImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCATELOGCONTIMPLSERVICE_QNAME, features);
    }

    public ProductCatelogContImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCatelogContImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductCatelogCont
     */
    @WebEndpoint(name = "ProductCatelogContImplPort")
    public ProductCatelogCont getProductCatelogContImplPort() {
        return super.getPort(new QName("http://aasoapexample.com/", "ProductCatelogContImplPort"), ProductCatelogCont.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCatelogCont
     */
    @WebEndpoint(name = "ProductCatelogContImplPort")
    public ProductCatelogCont getProductCatelogContImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://aasoapexample.com/", "ProductCatelogContImplPort"), ProductCatelogCont.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCATELOGCONTIMPLSERVICE_EXCEPTION!= null) {
            throw PRODUCTCATELOGCONTIMPLSERVICE_EXCEPTION;
        }
        return PRODUCTCATELOGCONTIMPLSERVICE_WSDL_LOCATION;
    }

}
