
package com.aasoapexample;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatelogCont", targetNamespace = "http://aasoapexample.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatelogCont {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.aasoapexample.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCont", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.GetProductCont")
    @ResponseWrapper(localName = "getProductContResponse", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.GetProductContResponse")
    @Action(input = "http://aasoapexample.com/ProductCatelogCont/getProductContRequest", output = "http://aasoapexample.com/ProductCatelogCont/getProductContResponse")
    public Product getProductCont(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProductCont", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.AddProductCont")
    @ResponseWrapper(localName = "addProductContResponse", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.AddProductContResponse")
    @Action(input = "http://aasoapexample.com/ProductCatelogCont/addProductContRequest", output = "http://aasoapexample.com/ProductCatelogCont/addProductContResponse")
    public boolean addProductCont(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "Product", targetNamespace = "")
    @RequestWrapper(localName = "updateProductCont", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.UpdateProductCont")
    @ResponseWrapper(localName = "updateProductContResponse", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.UpdateProductContResponse")
    @Action(input = "http://aasoapexample.com/ProductCatelogCont/updateProductContRequest", output = "http://aasoapexample.com/ProductCatelogCont/updateProductContResponse")
    public boolean updateProductCont(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProductCont", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.DeleteProductCont")
    @ResponseWrapper(localName = "deleteProductContResponse", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.DeleteProductContResponse")
    @Action(input = "http://aasoapexample.com/ProductCatelogCont/deleteProductContRequest", output = "http://aasoapexample.com/ProductCatelogCont/deleteProductContResponse")
    public boolean deleteProductCont(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.aasoapexample.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductCont", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.GetAllProductCont")
    @ResponseWrapper(localName = "getAllProductContResponse", targetNamespace = "http://aasoapexample.com/", className = "com.aasoapexample.GetAllProductContResponse")
    @Action(input = "http://aasoapexample.com/ProductCatelogCont/getAllProductContRequest", output = "http://aasoapexample.com/ProductCatelogCont/getAllProductContResponse")
    public List<Product> getAllProductCont();

}
